java.naming.factory.initial=com.rabbitmq.jms.admin.RMQObjectFactory
java.naming.provider.url=amqp://ggadmin:ggadmin123@rabbitmq:5672
connectionFactoryNames=RMQConnectionFactory

# Target the built-in AMQP topic exchange
topic.amq.topic=amq.topic