java.naming.factory.initial=com.rabbitmq.jms.admin.RMQObjectFactory
java.naming.provider.url=amqp://ggadmin:ggadmin123@rabbitmq:5672
connectionFactoryNames=RMQConnectionFactory
# Target a JMS Topic (which maps to the RabbitMQ Exchange)
topic.MyRabbitExchange=MyRabbitExchange